stages:
  - build

image: node:8.12
build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - dist/
      - node_modules/
  before_script:
    - npm install
  script:
    - npm run build
