stages:
  - build
  - push-image

variables:
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/k.szwarc/ns-games-api/$CI_COMMIT_REF_NAME:latest

image: node:8.12
build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - dist/
      - node_modules/
  before_script:
    - npm install
  script:
    - npm run build

build-image:
  stage: push-image
  image: docker:git
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE --target production .
    - docker push $CONTAINER_RELEASE_IMAGE
