version: "3.4"

services:
  ns-games-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ns-games-api-dev
    environment:
      - MONGO_URL=${NS_GAMES_DB_URL}
      - MONGO_DB=${NS_GAMES_DB}
      - MONGO_USER=${NS_GAMES_USER}
      - MONGO_PASSWORD=${NS_GAMES_PASSWORD}
    ports:
      - "3005:3005"
    volumes:
      - ./api:/ns-games-api/api

  ns-games-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ns-games-api-production
    restart: on-failure
    environment:
      - MONGO_URL=${NS_GAMES_DB_URL}
      - MONGO_DB=${NS_GAMES_DB}
      - MONGO_USER=${NS_GAMES_USER}
      - MONGO_PASSWORD=${NS_GAMES_PASSWORD}
    ports:
      - "3005:3005"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${NS_GAMES_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${NS_GAMES_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${NS_GAMES_DB}
    restart: on-failure
    volumes:
      - ./db/data:/data/db
      - ./db/backup:/mongo-dump

  ns-games-spreadsheet:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: ns-games-spreadsheet
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${NS_GAMES_DB_URL}
      - MONGO_DB=${NS_GAMES_DB}
      - MONGO_USER=${NS_GAMES_USER}
      - MONGO_PASSWORD=${NS_GAMES_PASSWORD}

